# Generated by Django 4.0.4 on 2022-05-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0002_alter_familiar_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='nacimiento',
            field=models.IntegerField(),
        ),
    ]
