# Generated by Django 4.0.4 on 2022-05-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0004_alter_familiar_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='nacimiento',
            field=models.DateField(),
        ),
    ]
